"""Generate Adieu's package identity catalog; no encounter policy is inferred.

The catalog contains native facts. Reference pacing and reconstructed encounter
quotas belong to the authored mission, not to the package extraction.
"""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / 'Dawn/src/state/activity/vanilla/adieu/catalog.h'


def render(raw):
    data = json.loads(raw)
    assert (data['activityIndex'], data['activityTag'], data['scenario'], data['packageHash']) == (
        288, 0x80B5E014, 0x80B5E01F, 0xD8A28814)
    hx = lambda n: f'0x{n:08X}U'
    fl = lambda v: f'{float(v):.9f}F'
    lines = ['// Generated by tools/vanilla/generate_adieu.py; package evidence, not live acceptance.',
        '#pragma once', '#include "../../coo/executor.h"', '#include "../../coo/dialogue_service.h"',
        '#include <array>', '#include <span>', '#include <string_view>',
        'namespace dawn::state::activity::vanilla::adieu {',
        f'inline constexpr std::string_view kEvidenceSha256="{hashlib.sha256(raw).hexdigest()}";',
        'inline constexpr std::string_view kPackage="mission_journey";',
        'inline constexpr std::int16_t kActivity=288;',
        'inline constexpr std::uint32_t kInvestment=0xB913ED3FU,kActivityTag=0x80B5E014U,kScenario=0x80B5E01FU;',
        'inline constexpr std::uint32_t kRoot=0xD8A28814U,kMain=0x8577EEB1U,kBank=0x80C2AB74U;',
        'inline constexpr std::uint8_t kBubble=3,kRegion=24;',
        'struct Binding {coo::Asset asset;std::uint32_t offset,component,sense,authority;std::uint8_t flags;std::string_view name;};',
        'inline constexpr Binding kBindings[]{']
    slots = {}
    for group in data['groups']:
        for s in group['slots']:
            key = (group['registry'], s['slotTypes'], s['slotIndices'])
            assert key not in slots, key
            slots[key] = s
            lines.append('    {{%s,%s,%d,%d},%s,%s,%s,%s,%d,%s},' % (
                hx(key[0]), hx(s['descriptorTags']), key[1], key[2], hx(s['descriptorOffsets']),
                hx(s['componentClasses']), hx(s['senseSchemas']), hx(s['authSchemas']), s['slotFlags'], json.dumps(s['name'])))
    lines += ['};',
        'struct Group {std::uint32_t key,tag;std::uint8_t bubble;bool topLevel;std::uint16_t hint;std::span<const Binding> slots;};',
        'inline constexpr Group kGroups[]{']
    offset = 0
    for g in data['groups']:
        count = len(g['slots'])
        if g['registry'] in (0xD8A28814,0x4786C0E0,0x8577EEB1) and count:
            lines.append('    {%s,%s,3,%s,UINT16_MAX,std::span(kBindings).subspan(%d,%d)},' % (hx(g['registry']),hx(g['objectTag']),str(g['topLevel']).lower(),offset,count))
        offset += count
    lines += ['};', 'constexpr std::uint8_t slot_flags(const Binding& b) noexcept {return b.flags;}',
        'constexpr const Binding* find(std::uint32_t key,std::uint16_t type,std::uint16_t slot) noexcept {',
        '    for(const auto& b:kBindings) {if(b.asset.registry==key && b.asset.type==type && b.asset.slot==slot) return &b;}return nullptr;', '}',
        'constexpr coo::Asset asset(std::uint32_t key,std::uint16_t type,std::uint16_t slot) noexcept {const auto* b=find(key,type,slot);return b?b->asset:coo::Asset{};}',
        'inline constexpr auto kDialogueAsset=asset(kRoot,53,2),kObjectiveAsset=asset(kRoot,68,0),kMusicAsset=asset(kRoot,11,1);',
        'struct Point {float x{},y{},z{};};',
        'struct Volume {coo::Asset asset;Point min,max;std::span<const Point> polygon;std::string_view name;};']
    for i, volume in enumerate(data['volumes']):
        assert len(volume['vertices']) >= 3
        lines.append(f'inline constexpr Point kPolygon{i}[]{{' + ','.join(
            '{' + ','.join(fl(v) for v in p) + '}' for p in volume['vertices']) + '};')
    lines.append('inline constexpr Volume kVolumes[]{')
    for i, v in enumerate(data['volumes']):
        lines.append('    {{%s,%s,60,%d},{%s},{%s},kPolygon%d,%s},' % (hx(v['registry']), hx(v['tag']),
            v['slot'], ','.join(fl(n) for n in v['min']), ','.join(fl(n) for n in v['max']), i, json.dumps(v['name'])))
    lines += ['};', 'constexpr coo::Asset volume(std::string_view name) noexcept {for(const auto& v:kVolumes) if(v.name==name) return v.asset;return {};}',
              'inline constexpr coo::DialogueRow kDialogue[]{']
    scene_rows = {row for scene in data['scenes'] for action in scene['actions'] for row in action.get('dialogueRows', [])}
    for row in data['dialogue']:
        lines.append('    {%s,%d,0,%s},' % (hx(row['selector']), row['durationMs'], str(row['row'] in scene_rows).lower()))
    lines += ['};', 'inline constexpr coo::DialogueDefinition kDialoguePolicy{kBank,kDialogue,{}};',
              'inline constexpr std::uint32_t kObjectives[]{' + ','.join(hx(v['event']) for v in data['objectives']) + '};',
              'struct Music {std::uint32_t name,bank,group,state;};', 'inline constexpr Music kMusic[]{']
    for m in data['music']:
        lines.append('    {' + ','.join(hx(m[k]) for k in ('nameHash', 'bank', 'stateGroup', 'state')) + '},')
    lines += ['};',
        'struct Movie {std::uint32_t registry,object,definition,offset;std::uint64_t sequenceIdentity;std::uint8_t bubble,region;};',
        'inline constexpr Movie kMovies[]{']
    for m in data['movies']:
        lines.append('    {%s,%s,%s,%s,0x%016XULL,%d,%d},' % (hx(m['registry']), hx(m['object']), hx(m['definition']), hx(m['offset']), m['sequenceIdentity'], m['bubble'], m['region']))
    lines += ['};', 'struct Scene {coo::Asset asset;std::uint32_t selector,graph,root;std::span<const coo::Asset> cast;std::span<const std::uint32_t> events,emitted;};']
    for i, scene in enumerate(data['scenes']):
        cast = []
        for member in scene['cast']:
            key = (member['registry'], member['type'], member['slot'])
            tag = slots.get(key, {}).get('descriptorTags', 0)
            cast.append('{%s,%s,%d,%d}' % (hx(key[0]), hx(tag), key[1], key[2]))
        lines.append(f'inline constexpr coo::Asset kCast{i}[]{{' + ','.join(cast) + '};')
        events = [e for e in scene['events'] if e != 0x385838EC]
        lines.append(f'inline constexpr std::array<std::uint32_t,{len(events)}> kInputs{i}{{' + ','.join(hx(e) for e in events) + '};')
        emitted = sorted({event for a in scene['actions'] for event in a.get('emittedEvents', [])})
        lines.append(f'inline constexpr std::array<std::uint32_t,{len(emitted)}> kEmitted{i}{{' + ','.join(hx(e) for e in emitted) + '};')
    lines.append('inline constexpr Scene kScenes[]{')
    for i, s in enumerate(data['scenes']):
        lines.append('    {asset(%s,43,%d),%s,%s,%s,kCast%d,kInputs%d,kEmitted%d},' % (hx(s['registry']), s['slot'], hx(s['selector']), hx(s['graph']), hx(s['graphRoot']), i, i, i))
    lines += ['};', 'struct Action {coo::Asset scene;std::uint32_t graph,root,node,definition,kind,event;};', 'inline constexpr Action kActions[]{']
    for s in data['scenes']:
        for a in s['actions']:
            if a['kind'] in (0x808062FE, 0x808062E4):
                assert len(a.get('emittedEvents', [])) <= 1
                lines.append('    {asset(%s,43,%d),%s,%s,%s,%s,%s,%s},' % (hx(s['registry']),s['slot'],hx(s['graph']),hx(s['graphRoot']),hx(a['prototype']),hx(a['definition']),hx(a['kind']),hx(next(iter(a.get('emittedEvents', [])),0))))
    lines += ['};', 'struct Source {coo::Asset asset;std::uint32_t definition,offset;std::uint16_t rule;std::uint8_t categories;bool hasRule,sceneOwned;};',
              'inline constexpr Source kSources[]{']
    owned = {(m['registry'], m['slot']) for s in data['scenes'] for m in s['cast'] if m['type'] == 1}
    for s in data['sources']:
        assert not s['unresolved'] and 1 <= len(s['categories']) <= 4
        rule = s['ruleRegistry'] == s['registry'] and s['ruleType'] == 66
        lines.append('    {asset(%s,1,%d),%s,%s,%d,%d,%s,%s},' % (hx(s['registry']), s['slot'], hx(s['tag']),hx(s['offset']),s['ruleSlot'] if rule else 0,
            len(s['categories']), str(rule).lower(), str((s['registry'], s['slot']) in owned).lower()))
    lines += ['};', '// Package facts do not establish original population quotas.',
        'constexpr bool unique_catalog() noexcept {',
        '    for(std::size_t i=0;i<std::size(kBindings);++i) for(std::size_t j=0;j<i;++j)',
        '        if(kBindings[i].asset==kBindings[j].asset) return false;',
        '    return true;', '}', 'static_assert(unique_catalog());',
        'static_assert(std::size(kMusic)==7 && std::size(kScenes)==15 && std::size(kDialogue)==32);', '}']
    return '\n'.join(lines) + '\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--evidence', type=Path, default=ROOT / 'build/coo/adieu-research/adieu-bindings.json')
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    result = render(args.evidence.read_bytes())
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding='utf-8') != result:
            raise SystemExit('Adieu catalog differs from supplied package evidence')
        print('Adieu catalog matches package evidence')
    else:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(result, encoding='utf-8')
        print(OUTPUT)


if __name__ == '__main__':
    main()
