"""Generate Dawn's Homecoming (mission_towerfall) native catalog from the extracted bindings.

Input:  build/coo/towerfall-research/towerfall-bindings.json (tools/coo/extract_towerfall_bindings.py)
Output: Dawn/src/state/activity/vanilla/homecoming/native_catalog.h

Everything emitted is a package fact (slot identities, descriptors, source categories, dialogue
selectors and windows, directive events, trigger volumes, scene casts, navigation points). The
reconstruction policy (which squads form an encounter, which objective they pursue, which scene
owns a source) lives in the module sources next to the mission graph, except the small tables
below that the generator needs to shape the records.
"""
import hashlib
import json
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
EVIDENCE = Path(os.environ.get('HOMECOMING_EVIDENCE', 'C:/Destiny 2 Development/build/coo/towerfall-research/towerfall-bindings.json'))
OUTPUT = ROOT / 'Dawn/src/state/activity/vanilla/homecoming/native_catalog.h'

# Squad sources whose actors are requested by an authored native Scene rather than loosely.
# Every source an authored Scene casts is scene-owned: the native Scene requests its one
# actor (frames vs the Cabal ship, the breach, Shaxx, Cayde, the Centurion, the hero moment,
# the post-gun guards, every civilian pose and reaction, the hangar fake fight and frames).
SCENE_OWNED = {
    0x9D8076E4: {1, 2, 3, 4, 6, 7, 15, 20, 24, 27, 28, 30, 32, 34, 35, 40, 41, 43, 44, 45, 46, 47, 48, 49, 50,
                 65, 66, 67, 84, 86, 88, 90, 92, 94, 96, 98, 100, 112, 114, 115},
    0xAA9D42BE: {66, 67, 68, 69, 71, 73, 75, 76},
    0x7BA8F95D: {17, 18, 19, 20, 21, 22},
    0x28A6B21F: {6, 10, 11, 14, 15, 16, 17, 30, 32},
}
# Combat objectives assigned before placement (Sunrise v40 encounter declarations).
OBJECTIVES = {
    0x9D8076E4: {**{s: (11, -1) for s in (6, 8, 9, 65, 66)}, **{s: (19, -1) for s in (20, 22, 23)},
                 **{s: (116, -1) for s in (112, 114, 115)}},
    0xAA9D42BE: {s: (1, -1) for s in range(4, 39)},
    0x7BA8F95D: {s: (1, -1) for s in (2, 3, 4, 5, 6, 7, 8, 11)},
    # obj_deck is the authored 24-row task for BOTH deck and ship interior.
    # Rows 10-18 reference interior/shield/escape providers 261-278. The native
    # cost pass selects a reachable row. Source 53 is Ghaul's cinematic cast.
    0x2D322467: {**{s: (0, -1) for s in range(4, 12)}, **{s: (1, -1) for s in range(12, 56) if s not in (33, 53)}, 33: (2, -1)},
    0x28A6B21F: {**{s: (9, 0) for s in (10, 11, 12, 13, 14, 15, 16, 17, 27)}, **{s: (43, 0) for s in range(28, 42)}},
}
# Cues dispatched by native cinematics/graphs/performers. Ikora's performer
# 80B3A848 embeds 66-69 AND the complete Ghost/Zavala pickup exchange (72).
# Requeueing 72 at child completion repeats the whole conversation.
NATIVE_OWNED_CUES = {0, 10, 21, 22, 23, 24, 66, 67, 68, 69, 72}
# Authored graph inputs the mission may deliver to each scene (package graph evidence).
SCENE_EVENTS = {
    (0x9D8076E4, 17): [0x6F51AC66], (0x9D8076E4, 14): [0x6F51AC66], (0x9D8076E4, 10): [0xAE7CC69C],
    (0x9D8076E4, 18): [0x6F51AC66], (0x7BA8F95D, 16): [0x84FFD4F6, 0x6F51AC66, 0x0B78A21A],
    # Parameter 0 is the friendly frame. Stage two also releases the
    # Cabal parameter 1's F9521E4E; stage one alone leaves it protected.
    (0x9D8076E4, 111): [0x38857CF3, 0x18EF2ABC],
    (0xAA9D42BE, 70): [0x18EF2ABC], (0xAA9D42BE, 72): [0x18EF2ABC],
    (0xAA9D42BE, 74): [0x18EF2ABC], (0xAA9D42BE, 77): [0x18EF2ABC],
    (0x28A6B21F, 2): [0xB8C5C0A5, 0x1BED1ED3], (0x28A6B21F, 4): [0xC021F76C], (0x28A6B21F, 5): [0xC021F76F],
}


def hx(v):
    return '0x%08XU' % v


def f(v):
    text = repr(float(v))
    if 'e' in text or 'E' in text:
        text = '%.9g' % float(v)
    if '.' not in text and 'e' not in text:
        text += '.'
    return text + 'F'


def main():
    raw = EVIDENCE.read_bytes()
    d = json.loads(raw)
    sha = hashlib.sha256(raw).hexdigest()
    groups = d['groups']
    lines = []
    w = lines.append
    w('// Generated by tools/vanilla/generate_homecoming.py. Native package facts.')
    w('#pragma once')
    w('#include <array>')
    w('#include <algorithm>')
    w('#include <span>')
    w('#include <string_view>')
    w('#include "../../coo/executor.h"')
    w('#include "../../coo/dialogue_service.h"')
    w('#include "../../coo/native_combatant_authority.h"')
    w('namespace dawn::state::activity::vanilla::homecoming {')
    w('inline constexpr std::string_view kEvidenceSha256="%s";' % sha)
    w('inline constexpr std::string_view kPackage="%s";' % d['package'])
    w('inline constexpr std::uint32_t kScenario=%s,kRoot=0x664128F4U,kPackageHash=%s,kBank=%s;' % (hx(d['scenario']), hx(d['packageHash']), hx(d['dialogueBank'])))
    w('// Names remain in the extraction evidence; runtime identities are native keys.')
    w('struct AssetBinding {coo::Asset asset;std::uint32_t offset,component,sense,authority;};')
    w('inline constexpr AssetBinding kAssets[]{')
    spans = []
    total = 0
    for g in groups:
        start = total
        for s in g['slots']:
            w('    {{%s,%s,%d,%d},%s,%s,%s,%s},' % (hx(g['registry']), hx(s['descriptorTags']), s['slotTypes'], s['slotIndices'],
                                                   hx(s['descriptorOffsets']), hx(s['componentClasses']), hx(s['senseSchemas']), hx(s['authSchemas'])))
            total += 1
        spans.append((g, start, total - start))
    w('};')
    w('inline constexpr std::string_view kAssetNames[]{')
    for g in groups:
        for s in g['slots']:
            w('    "%s",' % s['name'].replace('"', ''))
    w('};')
    w('static_assert(std::size(kAssetNames)==std::size(kAssets));')
    w('constexpr std::uint64_t asset_key(std::uint32_t registry,std::uint16_t type,std::uint16_t slot) noexcept {')
    w('    return (std::uint64_t{registry}<<32)|(std::uint64_t{type}<<16)|slot;')
    w('}')
    w('// Preserve authored catalogue order and wire slots. Only this lookup index is')
    w('// sorted; runtime resolution is bounded binary search instead of a full scan.')
    w('inline constexpr auto kAssetOrder=[] {')
    w('    std::array<std::uint16_t,std::size(kAssets)> order{};')
    w('    for(std::size_t i=0;i<order.size();++i) {order[i]=static_cast<std::uint16_t>(i);}')
    w('    std::sort(order.begin(),order.end(),[](auto a,auto b) {')
    w('        const auto& x=kAssets[a].asset;const auto& y=kAssets[b].asset;')
    w('        return asset_key(x.registry,x.type,x.slot)<asset_key(y.registry,y.type,y.slot);')
    w('    });')
    w('    return order;')
    w('}();')
    w('constexpr std::size_t catalog_index(std::uint32_t registry,std::uint16_t type,std::uint16_t slot) noexcept {')
    w('    const auto key=asset_key(registry,type,slot);std::size_t low=0,high=kAssetOrder.size();')
    w('    while(low<high) {')
    w('        const auto mid=low+(high-low)/2;const auto& a=kAssets[kAssetOrder[mid]].asset;')
    w('        const auto candidate=asset_key(a.registry,a.type,a.slot);')
    w('        if(candidate==key) {return kAssetOrder[mid];}')
    w('        if(candidate<key) {low=mid+1;} else {high=mid;}')
    w('    }')
    w('    return std::size(kAssets);')
    w('}')
    w('constexpr const AssetBinding* find(std::uint32_t registry,std::uint16_t type,std::uint16_t slot) noexcept {')
    w('    const auto i=catalog_index(registry,type,slot);return i<std::size(kAssets)?&kAssets[i]:nullptr;')
    w('}')
    w('constexpr coo::Asset asset(std::uint32_t registry,std::uint16_t type,std::uint16_t slot) noexcept {const auto* a=find(registry,type,slot);return a?a->asset:coo::Asset{};}')
    w('constexpr std::string_view asset_name(coo::Asset a) noexcept {const auto i=catalog_index(a.registry,a.type,a.slot);return i<std::size(kAssets)?kAssetNames[i]:std::string_view{};}')
    w('constexpr coo::Asset asset_named(std::uint32_t registry,std::uint16_t type,std::string_view name) noexcept {')
    w('    for(std::size_t i=0;i<std::size(kAssets);++i) {if(kAssets[i].asset.registry==registry && kAssets[i].asset.type==type && kAssetNames[i]==name) {return kAssets[i].asset;}}return {};')
    w('}')
    w('inline constexpr auto kDialogueAsset=asset(kRoot,53,2),kDirectiveAsset=asset(kRoot,68,0),kMusicAsset=asset(kRoot,11,1);')
    w('// Bank %s: selector, authored window (ms) and native ownership. Zero-window rows have no' % hx(d['dialogueBank']))
    w('// decoded speech and are never requested.')
    w('inline constexpr coo::DialogueRow kDialogue[]{')
    for row in d['dialogue']:
        w('    {%s,%d,0,%s},' % (hx(row['selector']), row['durationMs'], 'true' if row['row'] in NATIVE_OWNED_CUES else 'false'))
    w('};')
    w('inline constexpr coo::DialogueDefinition kDialoguePolicy{kBank,kDialogue,{}};')
    w('// Directive table %s rows in package order.' % hx(d['directiveTable']))
    w('inline constexpr std::uint32_t kObjectives[]{%s};' % ','.join(hx(o['event']) for o in d['objectives']))
    w('struct Point {float x{},y{},z{};};')
    w('struct Volume {coo::Asset asset;Point min,max;std::span<const Point> vertices;};')
    vols = d['volumes']
    for i, v in enumerate(vols):
        w('inline constexpr Point kPolygon%d[]{%s};' % (i, ','.join('{%s,%s,%s}' % tuple(f(c) for c in p) for p in v['vertices'])))
    w('inline constexpr Volume kVolumes[]{')
    for i, v in enumerate(vols):
        w('    {{%s,%s,60,%d},{%s,%s,%s},{%s,%s,%s},kPolygon%d},' % (hx(v['registry']), hx(v['tag']), v['slot'],
                                                              f(v['min'][0]), f(v['min'][1]), f(v['min'][2]),
                                                              f(v['max'][0]), f(v['max'][1]), f(v['max'][2]), i))
    w('};')
    w('inline constexpr std::string_view kVolumeNames[]{%s};' % ','.join('"%s"' % v['name'] for v in vols))
    w('static_assert(std::size(kVolumeNames)==std::size(kVolumes));')
    w('constexpr coo::Asset volume(std::uint32_t registry,std::uint16_t slot) noexcept {for(const auto& v:kVolumes) {if(v.asset.registry==registry && v.asset.slot==slot) {return v.asset;}}return {};}')
    w('constexpr coo::Asset volume_named(std::uint32_t registry,std::string_view name) noexcept {')
    w('    for(std::size_t i=0;i<std::size(kVolumes);++i) {if(kVolumes[i].asset.registry==registry && kVolumeNames[i]==name) {return kVolumes[i].asset;}}return {};')
    w('}')
    w('// Type-31 player triggers and the authored type-60 volume each one samples.')
    w('struct Trigger {std::string_view name;coo::Asset sensor,area;};')
    w('inline constexpr Trigger kTriggers[]{')
    for t in d['triggers']:
        area = 'volume(%s,%d)' % (hx(t['registry']), t['volume']) if t['volume'] is not None else 'coo::Asset{}'
        w('    {"%s",asset(%s,31,%d),%s},' % (t['name'], hx(t['registry']), t['slot'], area))
    w('};')
    w('constexpr coo::Asset trigger_area(std::uint32_t registry,std::string_view name) noexcept {')
    w('    for(const auto& t:kTriggers) {if(t.sensor.registry==registry && t.name==name) {return t.area;}}return {};')
    w('}')
    w('// Each populated category requests one actor; weighted template candidates are alternatives.')
    w('struct Spawn {std::uint16_t source;std::uint32_t registry,definition,offset;std::uint16_t rule;std::uint8_t count,categories;coo::native_combatant::TacticalGroup tactical;bool hasRule,sceneOwned;std::array<std::uint8_t,4> members;bool required{true};};')
    sources = d['sources']
    w('inline constexpr std::array<Spawn,%d> kSpawns{{' % len(sources))
    objective_slots = {(o['registry'], o['slot']): o for o in d['objectiveSlots']}
    for s in sources:
        cats = s['categories']
        count = sum(bool(c['selections'][0]) for c in cats)
        has_rule = s['ruleRegistry'] == s['registry'] and s['ruleType'] == 66
        rule = s['ruleSlot'] if has_rule else 0
        objective = OBJECTIVES.get(s['registry'], {}).get(s['slot'])
        if objective:
            assert (s['registry'], objective[0]) in objective_slots, (hex(s['registry']), objective)
            tactical = '{%s,%d,%d}' % (hx(s['registry']), objective[0], objective[1])
        else:
            tactical = '{}'
        scene_owned = s['slot'] in SCENE_OWNED.get(s['registry'], set())
        assert 1 <= len(cats) <= 4, (hex(s['registry']), s['slot'], len(cats))
        members = [int(bool(c['selections'][0])) for c in cats] + [0] * (4 - len(cats))
        w('    {%d,%s,%s,%d,%d,%d,%d,%s,%s,%s,{%s}},' % (s['slot'], hx(s['registry']), hx(s['tag']), s['offset'], rule, count, len(cats), tactical,
                                                      'true' if has_rule else 'false', 'true' if scene_owned else 'false', ','.join(str(m) for m in members)))
    w('}};')
    w('// Roster views share the asset records, preserving native order and slot numbers.')
    w('constexpr std::uint8_t slot_flags(const AssetBinding& s) noexcept {return (s.sense!=UINT32_MAX?1U:0U)|(s.authority!=UINT32_MAX?2U:0U);}')
    w('struct Group {std::uint32_t key,tag;std::size_t hint;bool topLevel;std::uint8_t bubble;std::span<const AssetBinding> slots;};')
    w('inline constexpr Group kGroups[]{')
    for g, start, n in spans:
        bubble = g['memberships'][0][0] if g['memberships'] else 0
        w('    {%s,%s,%d,%s,%d,std::span(kAssets).subspan(%d,%d)},' % (hx(g['registry']), hx(g['objectTag']), g['cacheIndex'] or 0,
                                                                  'true' if g['topLevel'] else 'false', bubble, start, n))
    w('};')
    w('struct Scene {coo::Asset asset;std::span<const coo::Asset> cast;std::span<const std::uint32_t> inputs;};')
    scenes = d['scenes']
    for i, sc in enumerate(scenes):
        cast = ','.join('{%s,0U,%d,%d}' % (hx(c['registry']), c['type'], c['slot']) for c in sc['cast'])
        if cast:
            w('inline constexpr coo::Asset kCast%d[]{%s};' % (i, cast))
        events = SCENE_EVENTS.get((sc['registry'], sc['slot']), [])
        if events:
            w('inline constexpr std::uint32_t kInputs%d[]{%s};' % (i, ','.join(hx(e) for e in events)))
    w('inline constexpr Scene kScenes[]{')
    for i, sc in enumerate(scenes):
        events = SCENE_EVENTS.get((sc['registry'], sc['slot']), [])
        w('    {{%s,%s,43,%d},%s,%s},' % (hx(sc['registry']), hx(sc['tag']), sc['slot'], 'kCast%d' % i if sc['cast'] else '{}', 'kInputs%d' % i if events else '{}'))
    w('};')
    w('// Generated native static navigation references; no world-coordinate overrides.')
    w('struct Navigation {std::string_view name;coo::Asset asset;};')
    w('inline constexpr Navigation kNavigation[]{')
    for n in d['navigation']:
        w('    {"%s",{%s,%s,47,%d}},' % (n['name'], hx(n['registry']), hx(n['object']), n['slot']))
    w('};')
    w('// Cinematic owners: bubble/state-1 objects the roster synthesizes (type 6, descriptor 0x2E8).')
    w('struct Movie {std::uint32_t registry,object,definition;std::uint8_t region,bubble;};')
    w('inline constexpr Movie kMovies[]{')
    for m in d['movies']:
        w('    {%s,%s,%s,%d,%d},' % (hx(m['registry']), hx(m['object']), hx(m['definition']), m['region'], m['bubble']))
    w('};')
    w('} // namespace dawn::state::activity::vanilla::homecoming')
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text('\n'.join(lines) + '\n', encoding='utf-8', newline='\n')
    print('wrote', OUTPUT, 'assets', total, 'volumes', len(vols), 'spawns', len(sources), 'scenes', len(scenes), 'triggers', len(d['triggers']))


if __name__ == '__main__':
    main()
